environment-defaults: &environment-defaults
  docker:
    - image: circleci/openjdk:8-jdk-browsers # Primary container -> all steps run on this
  environment:
    GRADLE_OPTS: "-Xms1024m -Xmx2048m -Dorg.gradle.daemon=false"
    JVM_OPTS: "-Xms1024m -Xmx2048m"
    _JAVA_OPTIONS: "-Xms1024m -Xmx2048m"
  working_directory: ~/komandante

commands:
  publish_artifacts:
    description: Publish Gradle project artifacts signed by provided GPG key
    parameters:
      base64_key:
        default: SIGNING_PGP_BASE64
        description: Variable that contains base64 encoded GPG file used for signing
        type: env_var_name
      deploy_task:
        default: sonaTypeUpload
        description: Gradle task to run to build, sign and upload artifacts
        type: string
      gpg_key_name:
        default: PGP_KEY
        description: Gpg key name to use for signing
        type: env_var_name

version: 2
jobs:
  build-test:
    <<: *environment-defaults
    steps:
      - checkout
      - restore_cache:
          keys:
            - komandante-{{ checksum "build.gradle" }}
            - komandante-
      - run: ./gradlew clean dependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: komandante-{{ checksum "build.gradle" }}
      - run: ./gradlew shadowJar
      - run:
          name:  Download cc-test-reporter
          command: |
            curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
            chmod +x ./cc-test-reporter
      - run: ./cc-test-reporter before-build
      - run: ./gradlew test --info --stacktrace
      - run:
          name: Upload code jacoco coverage as specified in build.gradle
          command: |
            JACOCO_SOURCE_PATH=src/main/kotlin ./cc-test-reporter format-coverage build/reports/jacoco/test/jacocoTestReport.xml --input-type jacoco
            ./cc-test-reporter upload-coverage
      - persist_to_workspace:
          root: ~/
          paths:
            - komandante/*

workflows:
  version: 2

  release-pipeline:
    jobs:
      - build-test